language: java
before_install:
  - cd java
install:
  -
addons:
  coverity_scan:
   project:
      name: draganagroj/rest
   build_command_prepend: ant fetch
   build_command: ant compile
    branch_pattern: master  
